
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/providers";
import Layout from "@/layout";
import Modal from "@/components/modal/modal";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Questions Application",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
        <Providers>
          <Layout>{children as JSX.Element}</Layout>
        </Providers>
      </body>
    </html>
  );
}
